$(document).ready(function(){
    $(".container").hide();
    $("#instagram").hide();
    $("#ig").hide();
    $(".btn-21").click(function(){
        $(".btn-21").fadeOut(1000).promise().done(function(){
            $(".container").fadeIn(1000);
            $("#instagram").fadeIn(1000);
            $("#ig").show();
        });
    })
});